[build]
builder = "railpack"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "always"

[env]
PORT = { default = "8000" }
RAILWAY_ENVIRONMENT = { default = "production" }
PYTHONPATH = { default = "/app/src" }
UV_SYSTEM_PYTHON = { default = "1" }
PYTHONFAULTHANDLER = { default = "1" }
PYTHONUNBUFFERED = { default = "1" }
PYTHONDONTWRITEBYTECODE = { default = "1" }

# Shared Variables (defined at project level)
DATABASE_URL = { default = "${{Neon.DATABASE_URL}}" }
REDIS_URL = { default = "${{Redis.REDIS_URL}}" }
COINDESK_API_KEY = { default = "${{shared.COINDESK_API_KEY}}" }

# Single service configuration - Railpack manages all processes
# All processes (web, worker, beat) are managed by start_processes.py
