services:
  # Main FastAPI Web Service
  - type: web
    name: bitcoin-newsletter-api
    runtime: python
    region: oregon
    plan: starter
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -e .
    startCommand: "crypto-newsletter serve --production --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        value: "postgresql+asyncpg://neondb_owner:npg_prKBLEUJ1f8P@ep-purple-firefly-ab009z0a-pooler.eu-west-2.aws.neon.tech/neondb"
      - key: REDIS_URL
        fromService:
          type: redis
          name: bitcoin-newsletter-redis
          property: connectionString
      - key: COINDESK_API_KEY
        value: "346bed562339e612d8c119b80e25f162386d81bdbe323f381a85eab2f0cb74fb"
      - key: ENVIRONMENT
        value: "production"
      - key: SERVICE_TYPE
        value: "web"
      - key: LOG_LEVEL
        value: "INFO"
      - key: DEBUG
        value: "false"
      - key: ENABLE_CELERY
        value: "true"
      - key: PYTHONPATH
        value: "/opt/render/project/repo/src"
    healthCheckPath: "/health"

  # Celery Worker Service
  - type: worker
    name: bitcoin-newsletter-worker
    runtime: python
    region: oregon
    plan: starter
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -e .
    startCommand: "crypto-newsletter worker"
    envVars:
      - key: DATABASE_URL
        value: "postgresql+asyncpg://neondb_owner:npg_prKBLEUJ1f8P@ep-purple-firefly-ab009z0a-pooler.eu-west-2.aws.neon.tech/neondb"
      - key: REDIS_URL
        fromService:
          type: redis
          name: bitcoin-newsletter-redis
          property: connectionString
      - key: COINDESK_API_KEY
        value: "346bed562339e612d8c119b80e25f162386d81bdbe323f381a85eab2f0cb74fb"
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: bitcoin-newsletter-redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          name: bitcoin-newsletter-redis
          property: connectionString
      - key: ENVIRONMENT
        value: "production"
      - key: SERVICE_TYPE
        value: "worker"
      - key: LOG_LEVEL
        value: "INFO"
      - key: DEBUG
        value: "false"
      - key: ENABLE_CELERY
        value: "true"
      - key: PYTHONPATH
        value: "/opt/render/project/repo/src"

  # Celery Beat Scheduler Service
  - type: worker
    name: bitcoin-newsletter-beat
    runtime: python
    region: oregon
    plan: starter
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -e .
    startCommand: "crypto-newsletter beat"
    envVars:
      - key: DATABASE_URL
        value: "postgresql+asyncpg://neondb_owner:npg_prKBLEUJ1f8P@ep-purple-firefly-ab009z0a-pooler.eu-west-2.aws.neon.tech/neondb"
      - key: REDIS_URL
        fromService:
          type: redis
          name: bitcoin-newsletter-redis
          property: connectionString
      - key: COINDESK_API_KEY
        value: "346bed562339e612d8c119b80e25f162386d81bdbe323f381a85eab2f0cb74fb"
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: bitcoin-newsletter-redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          name: bitcoin-newsletter-redis
          property: connectionString
      - key: ENVIRONMENT
        value: "production"
      - key: SERVICE_TYPE
        value: "beat"
      - key: LOG_LEVEL
        value: "INFO"
      - key: DEBUG
        value: "false"
      - key: ENABLE_CELERY
        value: "true"
      - key: PYTHONPATH
        value: "/opt/render/project/repo/src"

  # Redis service for Celery (PostgreSQL hosted externally on Neon)
  - type: redis
    name: bitcoin-newsletter-redis
    region: oregon
    plan: starter
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []  # Allow access from all Render services in this account

# Frontend Services
  # Admin Dashboard (React)
  - type: web
    name: bitcoin-newsletter-admin
    runtime: node
    region: oregon
    plan: starter
    buildCommand: |
      cd admin-dashboard
      npm install
      npm install -g serve
      cp .env.production .env.local
      npm run build
    startCommand: "cd admin-dashboard && npx serve -s dist -l $PORT"
    envVars:
      - key: VITE_API_URL
        value: "https://bitcoin-newsletter-api.onrender.com"
      - key: VITE_APP_ENV
        value: "production"
      - key: VITE_APP_VERSION
        value: "1.0.0"
    healthCheckPath: "/"
